=== hazto/valant-demo/apps/demo/src/maze-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "width": {
        "type": "integer"
      },
      "height": {
        "type": "integer"
      },
      "paths": {
        "type": "array",
        "items": [
          {
            "type": "object",
            "properties": {
              "x": {
                "type": "integer"
              },
              "y": {
                "type": "integer"
              },
              "isStart": {
                "type": "boolean"
              }
            },
            "required": [
              "x",
              "y",
              "isStart"
            ]
          },
          {
            "type": "object",
            "properties": {
              "x": {
                "type": "integer"
              },
              "y": {
                "type": "integer"
              }
            },
            "required": [
              "x",
              "y"
            ]
          },
          {
            "type": "object",
            "properties": {
              "x": {
                "type": "integer"
              },
              "y": {
                "type": "integer"
              }
            },
            "required": [
              "x",
              "y"
            ]
          },
          {
            "type": "object",
            "properties": {
              "x": {
                "type": "integer"
              },
              "y": {
                "type": "integer"
              }
            },
            "required": [
              "x",
              "y"
            ]
          },
          {
            "type": "object",
            "properties": {
              "x": {
                "type": "integer"
              },
              "y": {
                "type": "integer"
              }
            },
            "required": [
              "x",
              "y"
            ]
          },
          {
            "type": "object",
            "properties": {
              "x": {
                "type": "integer"
              },
              "y": {
                "type": "integer"
              }
            },
            "required": [
              "x",
              "y"
            ]
          },
          {
            "type": "object",
            "properties": {
              "x": {
                "type": "integer"
              },
              "y": {
                "type": "integer"
              }
            },
            "required": [
              "x",
              "y"
            ]
          },
          {
            "type": "object",
            "properties": {
              "x": {
                "type": "integer"
              },
              "y": {
                "type": "integer"
              },
              "isFinish": {
                "type": "boolean"
              }
            },
            "required": [
              "x",
              "y",
              "isFinish"
            ]
          }
        ]
      }
    },
    "required": [
      "name",
      "width",
      "height",
      "paths"
    ]
  }

=== hazto/valant-demo/apps/demo/src/test-map.json
{
    "name": "a test map",
    "width": 10,
    "height": 10,
    "paths": [
        { "x": 1, "y": 0, "isStart": true },
        { "x": 2, "y": 0 },
        { "x": 2, "y": 1 },
        { "x": 2, "y": 2 },
        { "x": 2, "y": 3 },
        { "x": 3, "y": 3 },
        { "x": 4, "y": 3 },
        { "x": 5, "y": 3, "isFinish": true }
    ]
}
